### ISSUE TITLE
Add a ask.toml config file 

### ISSUE THREAD

**Issue by damoonrashidi** [damoonrashidi/ask#3]
to control some of the runtime behaviour.

```toml
[commands]
enable_history = false
variations = 2

[shell]
always_use = "nushell"
fallback = "bash"
```
